/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Administrador
 */
public class VistaFinalizacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaFinalizacion
     */
    public VistaFinalizacion() {
        initComponents();
    }
    
    public VistaFinalizacion(int totalAlojamientos, int totalPersonas) {
        initComponents();
        setLocationRelativeTo(null);

        infoMessageLabel.setText(
                "<html><center>"
                + "Se han alquilado <b>" + totalAlojamientos + "</b> alojamientos<br>"
                + "para un total de <b>" + totalPersonas + "</b> personas."
                + "</center></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        ruralHomeLabel = new javax.swing.JLabel();
        felizEstanciaLabel = new javax.swing.JLabel();
        infoMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(380, 220));

        panelPrincipal.setBackground(java.awt.Color.white);
        panelPrincipal.setMaximumSize(null);
        panelPrincipal.setMinimumSize(null);
        panelPrincipal.setPreferredSize(null);
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        ruralHomeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ruralHomeLabel.setText("RuralHome...");
        panelPrincipal.add(ruralHomeLabel, new java.awt.GridBagConstraints());

        felizEstanciaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        felizEstanciaLabel.setText("feliz estancia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelPrincipal.add(felizEstanciaLabel, gridBagConstraints);

        infoMessageLabel.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelPrincipal.add(infoMessageLabel, gridBagConstraints);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFinalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFinalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFinalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFinalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFinalizacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel felizEstanciaLabel;
    private javax.swing.JLabel infoMessageLabel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel ruralHomeLabel;
    // End of variables declaration//GEN-END:variables
}
