/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Administrador
 */
public class VistaResultados extends javax.swing.JFrame {

    /**
     * Creates new form VistaResultados
     */
    public VistaResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCentro = new javax.swing.JPanel();
        scrollResultados = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        volverPrincipalButton = new javax.swing.JButton();
        finalizarAlquilerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultados de la búsqueda");

        panelCentro.setName(""); // NOI18N
        panelCentro.setPreferredSize(new java.awt.Dimension(400, 150));
        panelCentro.setLayout(new java.awt.BorderLayout());

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollResultados.setViewportView(tablaResultados);

        panelCentro.add(scrollResultados, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentro, java.awt.BorderLayout.PAGE_START);

        panelSur.setLayout(new java.awt.GridBagLayout());

        volverPrincipalButton.setText("Volver principal");
        volverPrincipalButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        volverPrincipalButton.setMaximumSize(new java.awt.Dimension(80, 23));
        volverPrincipalButton.setMinimumSize(new java.awt.Dimension(80, 23));
        volverPrincipalButton.setPreferredSize(new java.awt.Dimension(80, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        panelSur.add(volverPrincipalButton, gridBagConstraints);

        finalizarAlquilerButton.setText("Finalizar alquiler");
        finalizarAlquilerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finalizarAlquilerButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        finalizarAlquilerButton.setMaximumSize(new java.awt.Dimension(90, 23));
        finalizarAlquilerButton.setMinimumSize(new java.awt.Dimension(90, 23));
        finalizarAlquilerButton.setPreferredSize(new java.awt.Dimension(90, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        panelSur.add(finalizarAlquilerButton, gridBagConstraints);

        getContentPane().add(panelSur, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaResultados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finalizarAlquilerButton;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane scrollResultados;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JButton volverPrincipalButton;
    // End of variables declaration//GEN-END:variables

    public JTable getTablaResultados() {
        return tablaResultados;
    }

    public JButton getVolverPrincipalButton() {
        return volverPrincipalButton;
    }

    public JButton getFinalizarAlquilerButton() {
        return finalizarAlquilerButton;
    }
}
