package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.Provincia;
import modelo.TipoDeAlojamiento;

/**
 * 
 * author BERJANO MUÑOZ, RAFAEL
 * author BOZA VILLAR, RICARDO
 * author CALIXTO DEL HOYO, JUAN
 * author GARCÍA MARCHENA, ÁLVARO
 */
public class VistaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlojamientosAlta
     */
    public VistaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNorte = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        provinciaLabel = new javax.swing.JLabel();
        provinciaComboBox = new javax.swing.JComboBox();
        tipoAlojamientoLabel = new javax.swing.JLabel();
        tipoAlojamientoComboBox = new javax.swing.JComboBox();
        tipoDeUbicacionLabel = new javax.swing.JLabel();
        enPoblacionCheckBox = new javax.swing.JCheckBox();
        aisladoCheckBox = new javax.swing.JCheckBox();
        capacidadLabel = new javax.swing.JLabel();
        capacidadTxt = new javax.swing.JTextField();
        personasLabel = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        buscarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elija su alojamiento rural");
        setResizable(false);

        panelNorte.setBackground(java.awt.Color.white);
        panelNorte.setName("panelNorte"); // NOI18N
        panelNorte.setLayout(new java.awt.BorderLayout());

        tituloLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tituloLabel.setText("RURALHOME todo en turismo");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNorte.add(tituloLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(java.awt.Color.white);
        panelCentro.setName("panelCentro"); // NOI18N
        panelCentro.setLayout(new java.awt.GridBagLayout());

        provinciaLabel.setText("Provincia:");
        provinciaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelCentro.add(provinciaLabel, gridBagConstraints);

        provinciaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        provinciaComboBox.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelCentro.add(provinciaComboBox, gridBagConstraints);

        tipoAlojamientoLabel.setText("Tipo Alojamiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelCentro.add(tipoAlojamientoLabel, gridBagConstraints);

        tipoAlojamientoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoAlojamientoComboBox.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelCentro.add(tipoAlojamientoComboBox, gridBagConstraints);

        tipoDeUbicacionLabel.setText("Ubicación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        panelCentro.add(tipoDeUbicacionLabel, gridBagConstraints);

        enPoblacionCheckBox.setBackground(java.awt.Color.white);
        enPoblacionCheckBox.setText("En población");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCentro.add(enPoblacionCheckBox, gridBagConstraints);

        aisladoCheckBox.setBackground(java.awt.Color.white);
        aisladoCheckBox.setText("Aislada");
        aisladoCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCentro.add(aisladoCheckBox, gridBagConstraints);

        capacidadLabel.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        panelCentro.add(capacidadLabel, gridBagConstraints);

        capacidadTxt.setPreferredSize(new java.awt.Dimension(37, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCentro.add(capacidadTxt, gridBagConstraints);

        personasLabel.setText(" personas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelCentro.add(personasLabel, gridBagConstraints);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(java.awt.Color.white);
        panelSur.setLayout(new java.awt.GridBagLayout());

        buscarButton.setText("Buscar");
        panelSur.add(buscarButton, new java.awt.GridBagConstraints());

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsulta().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aisladoCheckBox;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel capacidadLabel;
    private javax.swing.JTextField capacidadTxt;
    private javax.swing.JCheckBox enPoblacionCheckBox;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JLabel personasLabel;
    private javax.swing.JComboBox provinciaComboBox;
    private javax.swing.JLabel provinciaLabel;
    private javax.swing.JComboBox tipoAlojamientoComboBox;
    private javax.swing.JLabel tipoAlojamientoLabel;
    private javax.swing.JLabel tipoDeUbicacionLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
    
    public JComboBox<Provincia> getProvinciaComboBox() { return provinciaComboBox; }
    public JComboBox<TipoDeAlojamiento> getTipoAlojamientoComboBox() { return tipoAlojamientoComboBox; }
    public JCheckBox getEnPoblacionCheckBox() { return enPoblacionCheckBox; }
    public JCheckBox getAisladoCheckBox() { return aisladoCheckBox; }
    public JTextField getCapacidadTxt() { return capacidadTxt; }
    public JButton getBuscarButton() { return buscarButton; }
}
